name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17] # Test against Java 11 and Java 17

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1 # Improve performance by limiting the checkout depth

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven' # Caches Maven dependencies for improved performance

    - name: Cache Ant dependencies
      uses: actions/cache@v3
      with:
        path: ~/.ant/cache
        key: ${{ runner.os }}-ant-${{ hashFiles('build.xml') }}
        restore-keys: |
          ${{ runner.os }}-ant-

    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
