# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17] # Tests for Java 11 and 17

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        fetch-depth: 1 # Limiting checkout depth -> improves efficiency 
        cache: 'maven' # Cache Maven dependencies 
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
